import {
  AlertOctagon,
  AlertTriangle,
  BatteryWarning,
  CheckCircle2,
  CircleSlash,
  Eye,
  HelpCircle,
  ShieldAlert,
  ShieldCheck,
  Wrench,
  XCircle,
  WifiOff,
  Gauge,
} from 'lucide-react';
import { Badge, type Tone } from '@iris/ui';
import { HEALTH_META, SENSOR_HEALTH_META } from '@iris/config';
import type { ConfidenceLevel, IncidentState, NodeHealth, QuorumStatus, RiskLevel, SensorHealth, SystemHealth } from '@iris/types';

const RISK_TONE: Record<RiskLevel, Tone> = { NORMAL: 'ok', WATCH: 'warn', HIGH: 'high', CRITICAL: 'crit' };
const RISK_ICON = {
  NORMAL: <CheckCircle2 className="h-3 w-3" aria-hidden />,
  WATCH: <Eye className="h-3 w-3" aria-hidden />,
  HIGH: <AlertTriangle className="h-3 w-3" aria-hidden />,
  CRITICAL: <AlertOctagon className="h-3 w-3" aria-hidden />,
};

export function RiskBadge({ level, prefix }: { level: RiskLevel; prefix?: string }) {
  return (
    <Badge tone={RISK_TONE[level]} icon={RISK_ICON[level]} aria-label={`${prefix ?? 'Severity'} ${level}`}>
      {level}
    </Badge>
  );
}

const CONF_TONE: Record<ConfidenceLevel, Tone> = { LOW: 'off', MEDIUM: 'info', HIGH: 'ai' };
export function ConfidenceBadge({ level, value }: { level: ConfidenceLevel; value?: number }) {
  return (
    <Badge tone={CONF_TONE[level]} icon={<Gauge className="h-3 w-3" aria-hidden />} aria-label={`Confidence ${level}`}>
      {level}
      {value !== undefined ? ` · ${(value * 100).toFixed(0)}%` : ''}
    </Badge>
  );
}

export function HealthBadge({ health }: { health: NodeHealth }) {
  const m = HEALTH_META[health];
  const tone: Tone = m.tone === 'ok' ? 'ok' : m.tone === 'warn' ? 'warn' : m.tone === 'off' ? 'off' : 'maint';
  const icon =
    health === 'HEALTHY' ? <CheckCircle2 className="h-3 w-3" aria-hidden /> : health === 'OFFLINE' ? <WifiOff className="h-3 w-3" aria-hidden /> : health === 'DEGRADED' ? <BatteryWarning className="h-3 w-3" aria-hidden /> : <Wrench className="h-3 w-3" aria-hidden />;
  return <Badge tone={tone} icon={icon}>{m.label}</Badge>;
}

export function SensorHealthBadge({ health }: { health: SensorHealth }) {
  const m = SENSOR_HEALTH_META[health];
  const tone: Tone = m.tone === 'ok' ? 'ok' : m.tone === 'warn' ? 'warn' : m.tone === 'bad' ? 'crit' : 'maint';
  return <Badge tone={tone}>{m.label}</Badge>;
}

const Q_META: Record<QuorumStatus, { label: string; tone: Tone; icon: React.ReactNode }> = {
  NONE: { label: 'No abnormality', tone: 'ok', icon: <ShieldCheck className="h-3 w-3" aria-hidden /> },
  SUSPICIOUS: { label: 'Suspicious', tone: 'warn', icon: <HelpCircle className="h-3 w-3" aria-hidden /> },
  CONFIRMED: { label: 'Confirmed', tone: 'crit', icon: <ShieldAlert className="h-3 w-3" aria-hidden /> },
  SUPPRESSED: { label: 'Down-weight / suppress', tone: 'maint', icon: <CircleSlash className="h-3 w-3" aria-hidden /> },
};
export function QuorumBadge({ status }: { status: QuorumStatus }) {
  const m = Q_META[status];
  return <Badge tone={m.tone} icon={m.icon}>{m.label}</Badge>;
}

const STATE_TONE: Record<IncidentState, Tone> = { WATCH: 'warn', HIGH: 'high', CRITICAL: 'crit', ACKNOWLEDGED: 'info', RESOLVED: 'ok' };
export function StateBadge({ state }: { state: IncidentState }) {
  const icon = state === 'RESOLVED' ? <CheckCircle2 className="h-3 w-3" aria-hidden /> : state === 'ACKNOWLEDGED' ? <Eye className="h-3 w-3" aria-hidden /> : <AlertTriangle className="h-3 w-3" aria-hidden />;
  return <Badge tone={STATE_TONE[state]} icon={icon}>{state}</Badge>;
}

export function SystemBadge({ health }: { health: SystemHealth }) {
  const tone: Tone = health === 'OPERATIONAL' ? 'ok' : health === 'DEGRADED' ? 'warn' : health === 'PARTIAL_OUTAGE' ? 'high' : 'crit';
  const icon = health === 'OPERATIONAL' ? <CheckCircle2 className="h-3 w-3" aria-hidden /> : health === 'OFFLINE' ? <XCircle className="h-3 w-3" aria-hidden /> : <AlertTriangle className="h-3 w-3" aria-hidden />;
  return <Badge tone={tone} icon={icon}>{health.replace('_', ' ')}</Badge>;
}

export function DemoTag({ className }: { className?: string }) {
  return (
    <Badge tone="maint" className={className} title="All values are generated by the ECO-SHIELD demo engine — not live field measurements.">
      Demo / Simulated
    </Badge>
  );
}
