#!/usr/bin/env node
/**
 * Generates local, git-ignored environment files with random secrets.
 * Nothing secret is ever committed: run this once per machine / deployment.
 *
 *   node scripts/gen-env.mjs            # writes apps/web/.env.local and apps/api/.env
 *   node scripts/gen-env.mjs --force    # overwrite existing files
 */
import { randomBytes } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const force = process.argv.includes('--force');

const rand = (n) => randomBytes(n).toString('base64url').replace(/[-_]/g, 'x').slice(0, n);
const secret = randomBytes(48).toString('base64url');

const users = [
  ['admin', 'ADMIN'],
  ['authority', 'AUTHORITY'],
  ['operator', 'OPERATOR'],
  ['steward', 'FIELD_STEWARD'],
  ['viewer', 'VIEWER'],
].map(([u, r]) => ({ u, r, p: rand(14) }));

const webEnv = [
  '# Generated by scripts/gen-env.mjs — DO NOT COMMIT',
  `IRIS_AUTH_SECRET=${secret}`,
  `IRIS_USERS=${users.map((x) => `${x.u}|${x.r}|${x.p}`).join(',')}`,
  'NEXT_PUBLIC_API_URL=http://localhost:8000',
  '',
].join('\n');

const apiEnv = [
  '# Generated by scripts/gen-env.mjs — DO NOT COMMIT',
  `IRIS_AUTH_SECRET=${secret}`,
  'IRIS_AUTH_REQUIRED=true',
  'IRIS_CORS_ORIGINS=http://localhost:3000',
  'IRIS_MQTT_ENABLED=false',
  '',
].join('\n');

function write(rel, content) {
  const p = join(root, rel);
  if (existsSync(p) && !force) {
    console.log(`skip   ${rel} (exists — use --force to overwrite)`);
    return false;
  }
  writeFileSync(p, content, { mode: 0o600 });
  console.log(`wrote  ${rel}`);
  return true;
}

const wroteWeb = write('apps/web/.env.local', webEnv);
write('apps/api/.env', apiEnv);

if (wroteWeb) {
  console.log('\nLocal demo accounts (shown once — also stored in apps/web/.env.local):');
  for (const x of users) console.log(`  ${x.r.padEnd(14)} ${x.u.padEnd(10)} ${x.p}`);
}
